version: '3'

services:
  evm-faucet:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      SHIMMEREVM_JSONRPC: ''
      SHIMMEREVM_CHAINID: ''
      PRIVATE_KEY: ''
    container_name: evm-faucet
    ports:
      - "8080:8080/tcp"
    restart: on-failure